---
platform: linux
inputs:
- name: git-repo
outputs:
- name: distribution-repository
caches:
- path: maven
- path: gradle
run:
  path: bash
  args:
    - -exc
    - |
      source /docker-lib.sh
      ${PWD}/git-repo/acceptance-tests/ci/scripts/build-skipper-server-with-drivers100.sh
params:
  ARTIFACTORY_USERNAME: ((artifactory-username))
  ARTIFACTORY_PASSWORD: ((artifactory-password))
  BASE_PATH: ((base-path))
